# To run all tests and repeat on each source change:
#   docker-compose --file=docker-compose-localdevelopment.yml up

version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.run
    ports: ["9000:9000"]
    tty: true
    volumes:
      # Develop on the current directory
      - .:/src
      # Exclude all target folders from the previous volume binding by explicitly binding them to an
      # empty volume
      - /src/app/shared/.jvm/target/
      - /src/app/shared/.js/target/
      - /src/app/js/shared/target/
      - /src/app/js/manualtests/target/
      - /src/app/js/webworker/target/
      - /src/app/js/client/target/
      - /src/app/jvm/target/
      - /src/project/target/
      - /src/project/project/target/
    command: >
      sbt -mem 2048 '; set javaOptions += "-Dconfig.file=conf/application-for-local-development.conf"; run 9000'

# Fixes Docker network issue: https://stackoverflow.com/a/62333327
networks: {default: {ipam: {config: [{subnet: 172.17.0.0/16}]}}}
