title: Disneyland Trivia!
image:  https://www.discoverlosangeles.com/sites/default/files/business/disneyland-park/c_fit-w_1920-h_1440-crm-la-disneyland0-6a3322105056a36_6a3323af-5056-a36f-23e7498faf405903.jpg
author: Josh # Change this to your name
#instructionsOnFirstSlide: 
masterSecret: bubbles # Remove this line to allow anyone to access the master controls
language: en # This is the default. The other supported languages can be found in application.conf

usageStatistics:
    # Set this to true if you're OK with sending anonymous usage statistics to the developer.
    #
    # The developer politely asks you to keep this so that they get a sense of how much this is
    # used.
    #
    # Unless you explicitly allow it below, the data sent to the developer will never contain
    # anything that identifies you personally. For example: It'll contain the version, the language,
    # and the number of players.
    sendAnonymousUsageDataAtEndOfQuiz: true

    # Uncomment these lines if you're fine with sending extra data to the developer of Quizmaster.
    #includeAuthor: true
    #includeQuizTitle: true

# Optional - Define custom defaults
defaults:
  maxTimeSeconds: 60
  pointsToGain: 1
  multipleAnswers_pointsToGainPerAnswer: 1
  multipleQuestions_pointsToGainPerQuestion: 1
  orderItems_pointsToGainInTotal: 1

rounds:
  - name: General Knowledge
    image: https://upload.wikimedia.org/wikipedia/commons/e/e6/Pixarpiersunset2019_%28cropped%29.jpg
    questions:
      - question: What year did Disneyland first open it's doors?
        questionDetail: 2 points for exact answer.  1 point if within 3 years.
        pointsToGain: 2
        image: https://i.pinimg.com/1200x/2a/2b/b6/2a2bb6d85a0d4bd0d7c24e216aa4e3a7.jpg
        answer: 1955

      - question: When are crowds at Disneyland the smallest?
        image: https://www.disneytouristblog.com/wp-content/uploads/2023/02/crowd-main-street-sleeping-beauty-castle-disneyland-california-068.jpg
        choices: [Late January, Mid April, Mid July, Late August]
        answer: Late January
        pointsToGain: 1

      - question: What was Disneyland Paris originally named?
        image: https://cdn.sortiraparis.com/images/80/87950/484853-visuels-disneyland-paris-chateau.jpg
        answer: Euro Disney
        pointsToGain: 1     
        
      - question: What is the best selling Disneyland merch item of all time?
        image: https://assets-prd.ignimgs.com/2023/02/10/disneymerch-1676047982279.png
        answer: Mickey Ears
        pointsToGain: 1          

      - question: Main Street is based on a small town in which US State?
        image: https://insidethemagic.net/wp-content/uploads/2020/09/msm123234SMALL-1.jpg
        choices: [Ohio, Missouri, California, West Virginia]
        answer: Missouri    

      - questionType: multipleAnswers
        question: List all the different "lands" in Disneyland.
        questionDetail: (Not including Main Street)
        answers:
          - Adventureland
          - New Orleans Square
          - Frontierland
          - Critter Country
          - Galaxy's Edge
          - Fantasyland
          - Toontown
          - Tomorrowland
        answersHaveToBeInSameOrder: false
        image: https://assets.simpleviewinc.com/simpleview/image/upload/c_limit,h_1200,q_75,w_1200/v1/crm/anaheimca/16921_imageb_c5e9346d-5056-a36a-07b05340b661147d.jpg
        pointsToGainPerAnswer: 1           

  - name: New Orleans Square
    questions:
      - question: What year did Pirates of the Caribbean open?
        image: https://ca-times.brightspotcdn.com/dims4/default/1e843a5/2147483647/strip/true/crop/1778x1000+0+0/resize/1200x675!/quality/75/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F85%2F49%2F0cd31493544658708d833cc8afb0%2Fla-1499393184-7cm3dj7cb8-snap-image
        choices: [1975, 1963, 1972, 1967]
        answer: 1967
        pointsToGain: 1

      - question: What is the name of the vehicle that takes you throughout the Haunted Mansion?
        image: https://cdn.vox-cdn.com/thumbor/UNTYDetg86-3bykWu_vNOmYQNdw=/0x0:4240x2832/1200x0/filters:focal(0x0:4240x2832):no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/18956932/16400040129_2ff8c1b0b6_o.jpg
        answer: Doom Buggies    

      - question: What are the ghostly residents of the Haunted Mansion referred to by the Ghost Host?
        image: https://static.wikia.nocookie.net/hauntedmasnion/images/3/37/HBG45457492LARGE-2.jpg
        answer: Happy Haunts

  - name: Fantasyland
    questions:
      - question: What was the original name for "It's a Small World" when Walt Disney conceived of it?
        image: https://people.com/thmb/8qyuGFAmm9xUOs6Za9MfafRhjP0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(299x0:301x2)/small-world-1600-97c0cb7dc4554375b2a7d2ea3022e68b.jpg
        choices: [All over the world, Children of the world, A wonderful world, World of color]
        answer: Children of the world

      - question: True or False?  Alice in Wonderland was Disneylands first ever two-level ride-through attraction?
        image: https://d23.com/app/uploads/2018/06/1180w-600h_061418_alice-in-wonderland-attraction-60th-anniversary.jpg
        choices: [True, False]
        answer: True      

      - question: How many times has the draw bridge of Sleeping Beauty's Castle been raised in it's lifetime?
        questionDetail: Yes, it is a real functional draw bridge
        image: https://yesterland.com/images-myths/insanefacts_drawbridge2014ww.jpg
        choices: [1, 2, 3, 4]
        answer: 2

      - question: What movie was Mr.Toads Wild Ride based off of?
        image: https://d23.com/app/uploads/2013/04/Mr-Toads-Wild-Ride-1180x600-1180x600.jpg
        answer: The adventures of Ichabod and Mr.Toad

  - name: General Knowledge Part 2
    questions:
      - question: What land is the Astro Orbitor located?
        image: https://www.tripsavvy.com/thmb/Ox42IoVZhu-WSwuVMHT5s1XtoOw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/P1161027-1000x1500-2-58f79c995f9b581d593ab1f6.jpg
        answer: Tomorrowland
        
      - question: What land is Big Thunder Mountain Railroad located?
        image: https://upload.wikimedia.org/wikipedia/commons/f/f5/Big_Thunder_Mountain_Entrance_Sign_at_Magic_Kingdom.jpg
        answer: Frontierland

      - question: Which was the first-ever attraction to use holograms?
        image: https://disneydose.com/wp-content/uploads/Rise-of-the-Resistance-3.jpg
        answer: Haunted Mansion

      - question: On the day of opening, who bought the very first Disneyland ticket?
        image: https://www.momrewritten.com/wp-content/uploads/2021/04/Disneyland-tickets-at-castle-LEAD-720x540.jpg.webp
        choices: [Walt Disney, Roy Disney, Marc Davis, Harriet Burns]
        answer: Roy Disney

  - name: Music Round
    questions:
      - question: What ride is this song from?
        answer: Pirates of the Caribbean
        audio: http://soundsofdisneyland.com/AudioFiles/Pirates%20of%20the%20Caribbean/18%20Medley.m4a

      - question: What ride is this song from?
        answer: Haunted Mansion
        audio: http://soundsofdisneyland.com/AudioFiles/Haunted%20Mansion/17%20Medley.m4a

      - question: What ride is this song from?
        answer: Guardians of the Galaxy
        audio: http://soundsofdisneyland.com/AudioFiles/Guardians%20of%20the%20Galaxy/01%20Summer%20of%20Heroes_%20Area%20Loop.m4a  

      - question: What ride is this song from?
        answer: Star Tours
        audio: http://soundsofdisneyland.com/AudioFiles/Star%20Tours/04%20The%20Adventures%20Continue_%20Queue%20Music%20(2011).mp3 

      - question: What ride is this song from?
        answer: Alice in Wonderland
        audio: http://soundsofdisneyland.com/AudioFiles/Alice%20in%20Wonderland/15%20March%20of%20the%20Cards%201.mp3

      - question: What ride is this song from?
        answer: Jungle Cruise
        audio: http://soundsofdisneyland.com/AudioFiles/Jungle%20Cruise/02%20Area%20Background%20Music.mp3

      - question: What ride is this song from?
        answer: Mark Twain River Boat
        audio: http://soundsofdisneyland.com/AudioFiles/Mark%20Twain%20River%20Boat/01%20Mark%20Twain%20River%20Boat_%20Queen%20of%20the%20River%20Theme.mp3

      - question: What ride is this song from?
        answer: Mark Twain River Boat
        audio: http://soundsofdisneyland.com/AudioFiles/It's%20a%20Small%20World/10%20Float%20Through.mp3







